package antimattaermod.core.ASM;

import com.google.common.eventbus.EventBus;
import cpw.mods.fml.common.DummyModContainer;
import cpw.mods.fml.common.LoadController;
import cpw.mods.fml.common.ModMetadata;

/**
 * @author C6H2Cl2
 */
public class AMMCoreDummyContainer extends DummyModContainer {
    public AMMCoreDummyContainer(){
        ModMetadata metadata = getMetadata();
        metadata.name = "AMMCore-ASM";
        metadata.modId = metadata.name.toLowerCase();
        metadata.version = "1.0.0";
        metadata.authorList.add("C6H2Cl2");
        setEnabledState(true);
        metadata.autogenerated = false;
    }

    @Override
    public boolean registerBus(EventBus bus, LoadController controller)
    {
        bus.register(this);
        return true;
    }

}
